### ISSUE TITLE
loadnppes.py not working correctly

### ISSUE THREAD

**Issue by flowersw** [HHSIDEAlab/provider-data-tools#13]
@aviars , I was attemping to load in the latest nppes data via this function to the registry server, and I got this error traceback

(pdt) [will@will-comp provider-data-tools]$ loadnppes.py y y 
<a class="skip" name="jump_content">Content
						Section</a>
<a href="http://www.cms.gov/Regulations-and-Guidance/HIPAA-Administrative-Simplification/NationalProvIdentStand/DataDissemination.html" target="new">http://www.cms.gov/Regulations-and-Guidance/HIPAA-Administrative-Simplification/NationalProvIdentStand/DataDissemination.html</a>
<a href="./NPPES_Data_Dissemination_July_2016.zip">NPPES Data Dissemination (July 12, 2016)</a>
<a href="./NPPES_Deactivated_NPI_Report_071216.zip">NPPES Data Dissemination - Monthly Deactivation Update - July 12, 2016</a>
<a href="./NPPES_Data_Dissemination_071116_071716_Weekly.zip">NPPES Data Dissemination - Weekly Update - 071116-071716</a>
Downloading 
http://: Invalid host name.
Unzip 
unzip:  cannot find or open , .zip or .ZIP.
Import pecos_address.csv
Traceback (most recent call last):
  File "/home/will/.virtualenvs/pdt/bin/loadnppes.py", line 104, in <module>
    do_update(process_full, download)
  File "/home/will/.virtualenvs/pdt/bin/loadnppes.py", line 71, in do_update
    call(["csv2pjson-public.py", main_file_to_import, json_output_dir ])
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

I tried it locally, and also tried using the master branch version, with no success. It's possible that I'm not invoking the function correctly. I know that it has worked in the past, have you run into this error?

**Comment by aviars** [comment]
uly and August were missing from the list of months.  I have fixed the and published a new version on GitHub and Pypi. https://pypi.python.org/pypi/pdt/0.7.6 Thanks for spotting this bug.
