### ISSUE TITLE
typo in file name pdt/pjson/validate-pjson-affilations 

### ISSUE THREAD

**Issue by helenaxwang** [HHSIDEAlab/provider-data-tools#2]
should be `validate-pjson-affiliations` (with an additional i). 

pip installing the package as is fails:
```
error: file '/private/tmp/pip-build-ixnHIs/pdt/pdt/pjson/validate-pjson-affiliations' does not exist
```

Install works after renaming the file.

**Comment by aviars** [comment]
Thanks @helenaxwang .  I've not fixed this in the new version 0.6.6.
