### ISSUE TITLE
[Question] Pecos compiled results

### ISSUE THREAD

**Issue by Germanaz0** [HHSIDEAlab/provider-data-tools#25]
How many results should be on compiled document ? because it is kinda slow to import, it takes like 1h per 1K of records and don't know if in there should be the 5M of records or is like just a few of data.

**Comment by aviars** [comment]
You need to add indexes first to speed up process. Number of results equals the number of lines in base.csv

**Comment by Germanaz0** [comment]
I am going to check the index, I am pretty sure that I have them, put Is it
normal to take a lot of Time ?

**Comment by aviars** [comment]
Should only take an hour or so...need indexes on the reassignment collection fields.

**Comment by Germanaz0** [comment]
Yes, it was the indexes, somehow I did not have all them, now works faster, thanks for help
